### ISSUE TITLE
Can't redirect output

### ISSUE THREAD

**Issue by osalbahr** [ArgentumCation/mirafetch#17]
```console
$ mirafetch > out.txt
Error: The cursor position could not be read within a normal duration
```

Steps to reproduce:
```console
% docker run -it rust
... clone and cd into the repo ...
root@d0614e0e0f6f:/mirafetch# cargo run > out.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/mirafetch`
Error: The cursor position could not be read within a normal duration
root@d0614e0e0f6f:/mirafetch# 
```

---

The error message seems to be trickling from [crossterm-rs/crossterm/src/cursor/sys/unix.rs#L50](https://github.com/crossterm-rs/crossterm/blob/08762b3ef4519e7f834453bf91e3fe36f4c63fe7/src/cursor/sys/unix.rs#L50).

Could be related to this upstream bug:
- https://github.com/crossterm-rs/crossterm/issues/367#issuecomment-1807706879

**Comment by ArgentumCation** [comment]
we draw the information and logo in separate steps so I don't think redirecting output is actually doable
